### ISSUE TITLE
WildInspect throws warn.

### ISSUE THREAD

**Issue by Firestone82** [BG-Software-LLC/WildInspect#2]
Hi, I have talked with creator of CoreProtect about that warn. He sas, that you are using page number 0 as default. And thats wrong.

![image](https://user-images.githubusercontent.com/57676764/110432706-c0f75980-80af-11eb-82f3-519e1e977cf9.png)

Could you please fix it?

Error: https://pastebin.com/9i7iXGrA

**Comment by OmerBenGera** [comment]
Check out latest dev build, should fix the issue.

**Comment by Firestone82** [comment]
Fixed

**Comment by Firestone82** [comment]
Ok, nvm. I found anotherthing,
 pages are not working. Its shows only 7 lines, then there should be page, but thats now showing.

![image](https://user-images.githubusercontent.com/57676764/111320760-9ab15b00-8667-11eb-9ce9-e0f415cb2cf1.png)

**Comment by OmerBenGera** [comment]
You're talking about the footer message?

**Comment by Firestone82** [comment]
From CoreProtect you can see that Page 1/3, but from WildInspect, its not showing it.

**Comment by OmerBenGera** [comment]
@Firestone82 Check out latest dev build, it should hopefully fix the issue

**Comment by Firestone82** [comment]
[23:04:05 INFO]: Firestone82 issued server command: /plot inspect
[23:04:06 WARN]: [WildInspect] Plugin WildInspect v2.3.3-DEVb15 generated an exception while executing task 1992
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:614) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:770) ~[?:?]
        at com.bgsoftware.wildinspect.coreprotect.CoreProtect.lambda$performLookup$1(CoreProtect.java:138) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Yatopia-17]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Yatopia-17]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Yatopia-17]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by OmerBenGera** [comment]
Fixed in latest dev build

**Comment by Firestone82** [comment]
Error is still showing. https://pastebin.com/nzVH96Qp
Have you tried using mysql? When I use SQL its working fine, but if I have coreprotect with mysql. It throws this error.

```
CoreProtect Settings:
---------------------

# MySQL is optional and not required.
# If you prefer to use MySQL, enable the following and fill out the fields.
use-mysql: true
table-prefix: cp_creative16_
mysql-host: IP
mysql-port: 3306
mysql-database: coreprotect
mysql-username: coreprotect
mysql-password: PASS
```

**Comment by OmerBenGera** [comment]
Hey, no - I didn't try it with MySQL, but I found what might cause it.
Check latest dev build, let me know if it fixes the issue

**Comment by Firestone82** [comment]
Finally fixed. Pages is showing and no warns in console. Nice. GJ.

**Comment by OmerBenGera** [comment]
> 
> 
> Finally fixed. Pages is showing and no warns in console. Nice. GJ.

Finally lol
If it happens again, make sure you post here and not on discord :)
